release:
  github:
    owner: digitalsleuth
    repo: crawin-salt
manifest:
  version: 2
  name: crawin
  base_dir: crawin
  modes:
    - name: addon
      state: crawin.addon
    - name: dedicated
      state: crawin.dedicated
      default: true
  supported_os:
    - id: windows
      release: 10
    - id: windows
      release: 11
  saltstack:
    pillars:
      crawin_user_template: "{{ .User }}"
      inpath_template: '{{ default "C:\standalones" .inpath }}'
